db.URL=jdbc:mysql://localhost:3306/loan_management?useSSL=false&serverTimezone=UTC
db.USER=root
db.PASSWORD=Admin@123

liquibase.changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
db.pool.minSize=2
db.pool.maxSize=10
db.pool.connectionTime=30000
db.pool.idleTimeout=3000
