db.url=jdbc:mysql://localhost:3306/loan_management?useSSL=false&serverTimezone=UTC
db.username=root
db.password=Admin@123

liquibase.change-log-file=src/main/resources/db/changelog/db.changelog-master.xml
db.pool.min-size=2
db.pool.max-size=10
db.pool.connection-time=30000
db.pool.idle-timeout=3000
